Feature/70
redwoodjs/sprout pull request #73
Opened 2022-05-04 15:07 UTC by noire-munich

2022-06-07 19:18 UTC, cannikin commented
I never got a user on the site so I added a couple of commits to allow access to that page as long as we're not in production!

2022-06-07 20:42 UTC, cannikin requested changes

2022-06-08 10:55 UTC, noire-munich commented
> I never got a user on the site so I added a couple of commits to allow access to that page as long as we're not in production!

Got you covered, you should have admin rights now.

2022-06-08 13:06 UTC, noire-munich commented on api/src/graphql/jobs.sdl.ts
> +    token: String!
Agreed.

Wasn't sure about how best to handle this. I opted for a directive on a field, but I have my doubts: it could also be on the Job type itself. Would you see a reason to do one in spite of the other?

2022-06-08 15:38 UTC, cannikin approved these changes

2022-06-08 15:39 UTC, cannikin commented
I've never written a custom directive before, but that one looks like a nice solve!

2022-06-08 15:39 UTC, merged